### ISSUE TITLE
error: cannot declare variable 'processor'

### ISSUE THREAD

**Issue by jhsiao21** [iamantony/qtcsv-example#3]
hi, I got an error when I execute the following command.

> # Build example binary.
> qmake ..\example\example.pro CONFIG+=release DESTDIR=%cd%
> mingw32-make

The error message is:
> ..\example\main.cpp: In function 'void ReadAndProcess(const QString&)':
> ..\example\main.cpp:84:21: error: cannot declare variable 'processor' to be of a
> bstract type 'ReadAndProcess(const QString&)::RevertProcessor'
>      RevertProcessor processor;
>                      ^
> ..\example\main.cpp:67:11: note:   because the following virtual functions are p
> ure within 'ReadAndProcess(const QString&)::RevertProcessor':
>      class RevertProcessor : public QtCSV::Reader::AbstractProcessor
>            ^
> In file included from ..\example\main.cpp:8:0:
> ..\qtcsv\include/qtcsv/reader.h:57:26: note:    virtual bool QtCSV::Reader::Abst
> ractProcessor::processRowElements(const QStringList&)
>              virtual bool processRowElements(const QStringList& elements) = 0;
>                           ^
> Makefile.Release:192: recipe for target 'release/main.o' failed
> mingw32-make[1]: *** [release/main.o] Error 1
> mingw32-make[1]: Leaving directory 'C:/Users/Administrator/Downloads/qtcsv-examp
> le-master/build'
> Makefile:36: recipe for target 'release' failed
> mingw32-make: *** [release] Error 2

So, I' can't build "example.exe" successfully. how to fix this problem? Tks.

**Comment by iamantony** [comment]
Hi! Thank you for the issue. 
Try to pull latest commits (don't forget to update subproject - qtcsv!) and build again.
