### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by thekatiemcneil** [iamantony/qtcsv-example#4]
I've built qtcsv on my machine (mac os x) seemly just fine, but I can't seem to run this example file. I keep getting an error "library not found for -lqtcsv" and after an hour of trying to figure out why, I haven't been able to. Any advice?

**Comment by iamantony** [comment]
Hello.
First of all check out build steps in _Readme_ file and in _.travis.yml_ (commands after _script:_).
If you have followed all the steps and still get an error, then in build folder search for _libqtcsv.so_ file. If it is not there, it means that you did not compiled it.
If library file exist, then in command `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/../qtcsv;` replace `LD_LIBRARY_PATH` with `DYLD_LIBRARY_PATH`.
If it doesn't help, just copy _libqtcsv.so_ (and _libqtcsv.so.1.X.Y_ if it exist) to folder with _example_ executable.
